apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnectS2I
metadata:
  name: my-connect-cluster
  namespace: techno-proj
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  version: 2.5.0
  replicas: 1
  # TODO: change bootstrap servers below. Find yours inside Kafka's YAML.
  bootstrapServers: my-cluster-kafka-bootstrap.techno-proj.svc:9092, my-cluster-kafka-bootstrap.techno-proj.svc:9093
tls:
  trustedCertificates:
    - secretName: my-cluster-cluster-ca-cert
      certificate: ca.crt

i
